spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update  # Automatically create/update database tables based on entities
    show-sql: true  # Show SQL queries in the logs
    database-platform: org.hibernate.dialect.H2Dialect
